version: 2

sources:
  - name: raw
    tables:
    - name: raw_contracts
      description: Raw contracts data
      columns:
        - name: contract_number
          description: Primary key for contracts
          tests:
            - unique
            - not_null
            - dbt_expectations.expect_column_values_to_be_in_type_list:
                column_type_list: [varchar]
            - dbt_expectations.expect_column_to_exist
        - name: client_id
          tests:
            - dbt_expectations.expect_column_values_to_be_in_type_list:
                column_type_list: [varchar]
            - dbt_expectations.expect_column_to_exist
        - name: principal_amount
          tests:
            - dbt_expectations.expect_column_values_to_be_in_type_list:
                column_type_list: [double]
            - dbt_expectations.expect_column_to_exist

    - name: raw_customers
      description: Raw customers data
      columns:
        - name: client_id
          description: Primary key for customers
          tests:
            - unique
            - not_null

    - name: raw_installments
      description: Raw installments data
      columns:
        - name: installment_id
          description: Primary key for installments
          tests:
            - unique
            - not_null
        - name: contract_number
          description: Foreign key to contracts
          tests:
            - not_null

    - name: raw_product_types
      description: Raw product types data
      columns:
        - name: product_type_id
          description: Primary key for product types
          tests:
            - unique
            - not_null

    - name: raw_products
      description: Raw products data
      columns:
        - name: product_code
          description: Primary key for products
          tests:
            - unique
            - not_null
        - name: product_type_id
          description: Foreign key to product types
          tests:
            - not_null

    - name: raw_regions
      description: Raw regions data
      columns:
        - name: region_id
          description: Primary key for regions
          tests:
            - unique
            - not_null

    - name: raw_repayments
      description: Raw repayments data
      columns:
        - name: repayment_id
          description: Primary key for repayments
          tests:
            - unique
            - not_null
        - name: installment_id
          description: Foreign key to installments
          tests:
            - not_null