version: 2

sources:
  - name: raw
    freshness: 
      error_after:
        count: 2
        period: day
      warn_after:
        count: 1
        period: day
    loaded_at_field: ingest_timestamp
    tables:
    - name: raw_contracts
      description: Raw contracts data
      columns:
        - name: contract_number
          description: Primary key for contracts
          tests:
            - unique
            - not_null

    - name: raw_customers
      description: Raw customers data
      columns:
        - name: client_id
          description: Primary key for customers
          tests:
            - unique
            - not_null

    - name: raw_installments
      description: Raw installments data
      columns:
        - name: installment_id
          description: Primary key for installments
          tests:
            - unique
            - not_null
        - name: contract_number
          description: Foreign key to contracts
          tests:
            - not_null

    - name: raw_product_types
      description: Raw product types data
      columns:
        - name: product_type_id
          description: Primary key for product types
          tests:
            - unique
            - not_null

    - name: raw_products
      description: Raw products data
      columns:
        - name: product_code
          description: Primary key for products
          tests:
            - unique
            - not_null
        - name: product_type_id
          description: Foreign key to product types
          tests:
            - not_null

    - name: raw_regions
      description: Raw regions data
      columns:
        - name: region_id
          description: Primary key for regions
          tests:
            - unique
            - not_null

    - name: raw_repayments
      description: Raw repayments data
      columns:
        - name: repayment_id
          description: Primary key for repayments
          tests:
            - unique
            - not_null
        - name: installment_id
          description: Foreign key to installments
          tests:
            - not_null